-- Popula o catalogo de exames a partir da aba ExameTab da planilha RegistroClinico.xlsx.
-- Campos de origem: NomeExame, Unidade, Limites, Descricao, NomeGrupo, Pos.

insert into exam_groups (name)
values
  ('Antropometria'),
  ('Bilirrubinas Total e Frações'),
  ('Básicos'),
  ('Coagulograma'),
  ('Ecocardiograma'),
  ('Eritrograma'),
  ('Específicos'),
  ('Função Renal'),
  ('Leucograma'),
  ('Lipidograma'),
  ('Marcadores Inflamatórios'),
  ('Marcadores Tumorais'),
  ('Plaquetograma'),
  ('Próstata'),
  ('Sinais Vitais'),
  ('Sumário de Urina-EQ'),
  ('Sumário de Urina-M')
on conflict (name) do nothing;

with exam_seed (name, group_name, unit, description, reference_range, source_position) as (
  values
    ('25-Hidroxivitamina D', 'Específicos', 'ng/dL', null, 'Normal 30 a 100 ng/dL, Insuficiente 20 a 29 ng/dL e Deficiente <20 ng/dL', 1),
    ('Abumina', 'Específicos', 'g/dL', null, '3,5 a 5,2 g/dL', 2),
    ('Ácido ascórbico', 'Sumário de Urina-EQ', '0=Negativo e 1=Positivo', null, null, 11),
    ('Ácido Láctico', 'Marcadores Inflamatórios', 'mg/dL', null, 'Plasma Venoso: 4,5 a 19,8 mg/dL e Plasma Arterial: 4,5 a 14,4 mg/dL', 3),
    ('Ácido Úrico', 'Básicos', 'mg/L', null, '3,4 a 7,0 mg/dL', 1),
    ('Albumina', 'Específicos', 'g/dL', null, '3,2 a 4,8 g/dL', 3),
    ('Alfa Fetoproteina', 'Marcadores Tumorais', 'ng/dL', 'É um marcador tumoral útil, sobretudo, na monitorização do tratamento do carcinoma hepatocelular e de tumores germinativos gonadais e extragonadais.', '<7,0 ng/mL', 2),
    ('ALT/TGP', 'Específicos', 'U/L (37ºC)', null, 'Até 41 U/L (37ºC)', 4),
    ('Altura', 'Antropometria', 'cm', null, null, 1),
    ('AST/TGO', 'Específicos', 'U/L (37ºC)', null, 'Até 40 U/L (37ºC)', 5),
    ('Atividade Ezimática', 'Coagulograma', '%', null, null, 11),
    ('Atividade Protrombínica', 'Coagulograma', '%', null, null, 1),
    ('Bactérias', 'Sumário de Urina-M', '/uL', null, '<550,0 /uL', 5),
    ('Basófilos', 'Leucograma', '%', null, null, 11),
    ('Bastonetes', 'Leucograma', '%', 'Nível de bastonetes alto no hemograma pode ser sinal uma infecção bacteriana aguda. ... Porém, se o número de bastonetes estiver mais alto que o de segmentados, significa que a medula óssea não está conseguindo enviar para o sangue uma quantidade suficiente de neutrófilos maduros, liberando os imaturos.', '0 a 5 %', 4),
    ('Bilirrubina D', 'Bilirrubinas Total e Frações', 'mg/dL', 'O exame de bilirrubina auxilia o diagnóstico de problemas no fígado, vias biliares ou anemia hemolítica, por exemplo, já que a bilirrubina é produto da destruição das hemácias e para ser eliminada pelo organismo necessita ser conjugada a um açúcar no fígado e sofrer a ação da bile.', 'Até 0,20 mg/dL', 1),
    ('Bilirrubina I', 'Bilirrubinas Total e Frações', 'mg/dL', null, 'Até 0,90 mg/dL', 2),
    ('Bilirrubina T', 'Bilirrubinas Total e Frações', 'mg/dL', null, 'Até 1,10 mg/dL', 3),
    ('Bilirrubinas', 'Sumário de Urina-EQ', 'mg/dL', null, '<1 mg/dL', 6),
    ('CA-125', 'Marcadores Tumorais', 'UI/mL', null, '< 35 UI/mL', 3),
    ('CA-19.9', 'Marcadores Tumorais', 'UI/mL', null, '< 37 UI/mL', 4),
    ('Cálcio', 'Específicos', 'mg/dL', null, '8,8 a 10,2 mg/dL', 6),
    ('Cálcio Iônico', 'Específicos', 'mg/dL', null, '4,61 a 5,17 mg/dL', 7),
    ('CC -Creatinina Soro', 'Função Renal', 'mg/dL', null, null, 10),
    ('CC -Creatinina Urina', 'Função Renal', 'mg/dL', null, null, 11),
    ('CC Depuração', 'Função Renal', 'ml/min/ 1,73m2', null, null, 13),
    ('CC Sup. Corp.', 'Função Renal', 'm2', null, null, 12),
    ('CC Volume', 'Função Renal', 'mL', 'Clearence de Creatinina  - CC', null, 9),
    ('CEA', 'Marcadores Tumorais', 'nanog/mL', 'Antigeno Carcino Embriogenico', '<3', 1),
    ('Células Epiteliais', 'Sumário de Urina-M', '/uL', null, null, 3),
    ('Cetonas', 'Sumário de Urina-EQ', 'mg/dL', null, '<10 mg/dL', 5),
    ('CHCM', 'Eritrograma', 'g/dL', 'CHCM é a sigla para Concentração da Hemoglobina Corpuscular Média. No hemograma, os valores de CHCM servem para verificar a quantidade de hemoglobina presente nas hemácias, também conhecidas como eritrócitos ou glóbulos vermelhos. A hemoglobina é uma proteína que se liga ao oxigênio, permitindo aos 
eritrócitos executar a sua função de transportar o oxigênio dos pulmões 
para os tecidos do corpo.', '32 a 36 g/dL de glóbulos', 6),
    ('Cilindros Hialinos', 'Sumário de Urina-M', '/uL', null, null, 4),
    ('Cintura', 'Antropometria', 'cm', null, null, 3),
    ('CK MB Massa', 'Específicos', 'ng/mL', null, '< 4,87 ng;mL', 29),
    ('CK Total', 'Específicos', 'U/L (37ºC)', null, '39 a 308 U/L (37º)', 8),
    ('Cloreto', 'Específicos', 'mmol/L', null, '98  a 107', 9),
    ('Colesteroal não-HDL', 'Lipidograma', 'mg/dL', null, 'Baixo:<160 mg/dL, Intermediario:<130 mg/dL, Alto:<100 mg/dL e Muito Alto:80 mg/dL', 5),
    ('Colesterol HDL', 'Lipidograma', 'mg/L', 'Bom', 'Adultos: >40 mg/dL , Crianças e Adolecentes: >45 mg/dL', 3),
    ('Colesterol LDL', 'Lipidograma', 'mg/L', 'Ruim', 'Risco: Baixo <130, Intermediário<100, Alto<70 e Muito Alto<50', 2),
    ('Colesterol Total', 'Lipidograma', 'mg/L', null, 'Adulto <190mg/dL e Criança e adolescente <170mg/dL', 1),
    ('Colesterol VLDL', 'Lipidograma', 'mg/L', 'Valores elevados no sangue levam ao acúmulo de gordura nas artérias e formação de placas de aterosclerose, aumentando o risco de doenças do coração.', 'Normal: 2 a 30 mg/dL e Alto:>30 mg/dL', 4),
    ('Concentração de Hem. Corp. Média', 'Específicos', 'g/dL', null, '32,4 a 36,0', 30),
    ('Cortisol', 'Específicos', 'mcg/dL', null, 'Matutino: entre 7 e 9 horas 5,3 a 22,5 mcg/dL - Vespertino: entre 15 e 17 horas de 3,4 a 16,8 mcg/dL', 39),
    ('Creatinina', 'Função Renal', 'mg/mL', null, '0,70 a 1,20  mg/dL', 1),
    ('Creatinina Fosfoquinase', 'Específicos', 'U/L (37°C)', null, null, 10),
    ('Densidade', 'Sumário de Urina-EQ', null, null, '< 1030', 1),
    ('Diâmetro Aorta', 'Ecocardiograma', 'mm', null, '<38mm', 1),
    ('Diâmetro Átrio Esquerdo', 'Ecocardiograma', 'mm', null, '<40mm', 2),
    ('Diâmetro Diastólico F. do VE', 'Ecocardiograma', 'mm', null, '<57mm', 3),
    ('Diâmetro Sistólico F. do VE', 'Ecocardiograma', 'mm', null, null, 4),
    ('Eosinófilos', 'Leucograma', '%', null, 'Eosinófilos são um tipo de glóbulo branco envolvido na resposta imunológica, especialmente em reações alérgicas e combate a parasitas. Normalmente, constituem cerca de 1-4% dos leucócitos no sangue. Contagens normais de eosinófilos variam de 100 a 400 células por microlitro de sangue. Valores acima desse intervalo podem indicar alergias, infecções parasitárias ou outras condições médicas.', 10),
    ('Eritrócitos', 'Eritrograma', 'milhões/mm3', null, '4.30 a 6.00 milhões/mm3', 1),
    ('Espessura relativa', 'Ecocardiograma', null, null, '<43', 5),
    ('Ferritina', 'Específicos', 'ng/dL', null, '30 a 400 ng/dL', 11),
    ('Ferro Sérico', 'Específicos', 'ug/d', 'u  = micro', '59,0 a 158,0 ug/dL', 12),
    ('Fosfatase Alcalina', 'Específicos', 'U/L (37ºC)', null, '40  a 130 I/L (37ºC)', 13),
    ('Fósforo', 'Específicos', 'mg/dL', null, '2,5 a 4,5 mg/dL', 14),
    ('Fração de Ejeção (Teichholz)', 'Ecocardiograma', '%', null, '>50%(Simpson) e >55 (Teichholz)', 6),
    ('Frequência Cardiaca', 'Sinais Vitais', 'bpm', null, null, 4),
    ('Gama GT', 'Específicos', 'U/L (37ºC)', 'O exame GGT, também conhecido por Gama GT ou gama glutamil transferase, é normalmente solicitado para verificar a presença de problemas no fígado ou obstrução biliar, já que nessas situações a concentração de GGT está elevada', '8 a 61 U/L (37ºC)', 15),
    ('Gliadina IgA', 'Específicos', 'U/mL', null, '<7 U/mL', 35),
    ('Glicemia em jejum', 'Específicos', 'mg/lL', null, 'Normal: 70 a 99 mg/dL, Tolerância: 100 a 125 mg/dL e Diabetes?: >125 mg/dL', 16),
    ('Glicemia Jejum', 'Básicos', 'mg/dL', 'A glicose é um açúcar simples essencial ao corpo humano, sendo a principal fonte de energia para as células. Os níveis normais de glicose no sangue em jejum variam entre 70 e 99 mg/dL. Valores entre 100 e 125 mg/dL indicam pré-diabetes, enquanto níveis de 126 mg/dL ou mais sugerem diabetes. Monitorar esses níveis é crucial para prevenir e gerenciar condições de saúde como a diabetes.', '75 a 99 mg/dL', 2),
    ('Glicemia Média Estimada', 'Específicos', null, null, null, 17),
    ('Glicose', 'Básicos', 'mg/L', 'A glicose é um açúcar simples essencial ao corpo humano, sendo a principal fonte de energia para as células. Os níveis normais de glicose no sangue em jejum variam entre 70 e 99 mg/dL. Valores entre 100 e 125 mg/dL indicam pré-diabetes, enquanto níveis de 126 mg/dL ou mais sugerem diabetes. Monitorar esses níveis é crucial para prevenir e gerenciar condições de saúde como a diabetes.', '110', 3),
    ('Glicose urina', 'Sumário de Urina-EQ', 'mg/dL', null, '<50 mg/dL', 4),
    ('Glicose, Plasma (fluoreto)', 'Específicos', 'mg/dL', null, '70 a 99 mg/dL', 33),
    ('Globulina Ligadora de Hormônios Sexuais', 'Específicos', 'nmol/L', null, 'Homem: (21 a 59) 14,6 a 94,6 ; (50 a 89) 21,6 a 113,1', 38),
    ('HCM', 'Eritrograma', 'pg', 'HCM (Hemoglobina Corpuscular Média) é uma medida do conteúdo médio de hemoglobina em cada glóbulo vermelho no sangue. Ela é calculada dividindo-se a hemoglobina total pelo número de glóbulos vermelhos. O valor normal do HCM varia entre 27 e 33 picogramas por célula. Valores anormalmente altos ou baixos de HCM podem indicar diversas condições, como anemia microcítica ou macrocítica, respectivamente. Essa medida é útil no diagnóstico e no monitoramento de diferentes tipos de anemia e outras doenças hematológicas', '27.0 a 33.0 pg', 5),
    ('Hemácias', 'Sumário de Urina-M', 'por campo', null, '< 5 por campos', 1),
    ('Hematócrito', 'Eritrograma', '% (v/v)', null, '41.0 a 54.0 % v/v', 3),
    ('Hemoglobina', 'Eritrograma', 'g/dL', null, '13.5 a 17.8 g/dL', 2),
    ('Hemoglobina Corpuscular Média', 'Específicos', 'pg', null, '27,7 a 32,7', 29),
    ('Hemoglobina Glicada', 'Específicos', '%', 'A hemoglobina glicada (HbA1c) é uma forma de hemoglobina ligada à glicose, usada para medir o controle glicêmico em pacientes diabéticos. Ela reflete a média dos níveis de glicose no sangue nos últimos dois a três meses. Valores elevados de HbA1c indicam um controle inadequado do diabetes, enquanto valores dentro do intervalo recomendado indicam bom controle. O teste de HbA1c é importante para ajustar tratamentos e prevenir complicações a longo prazo.', '4,0 a 6,0 %', 18),
    ('Hemoglobina urina', 'Sumário de Urina-EQ', 'mg/dL', null, '< 0,1 mg/dL', 8),
    ('Hormônio Luteinizante', 'Específicos', 'mUI/ml', 'O hormônio luteinizante (LH) é produzido pela hipófise anterior e atua no controle da função reprodutiva por meio do eixo hipotálamo–hipófise–gônadas. Nos homens, estimula as células de Leydig a produzirem testosterona, essencial para a espermatogênese e características sexuais secundárias. Nas mulheres, o pico de LH desencadeia a ovulação e mantém o corpo lúteo, responsável pela secreção de progesterona. Sua liberação é regulada pelo GnRH e modulada por mecanismos de feedback hormonal. Alterações nos níveis de LH indicam disfunções gonadais, hipofisárias ou efeitos farmacológicos.', '0,3 a 15,1', 41),
    ('IL - Glicemia a 30 min.', 'Específicos', 'mg/dL', null, null, 33),
    ('IL - Glicemia a 60 min.', 'Específicos', 'mg/dL', null, null, 34),
    ('IL - Glicemia em jejum', 'Específicos', 'mg/dL', null, null, 32),
    ('IL - Lactose', 'Específicos', 'g', 'Quantidade de lactose administrada. Se as glicemias seguintes a de jejum, não for superior a mais de 20 mg/dL, o paciente é portador de intolerância à lactose.', null, 31),
    ('Índice de Massa', 'Ecocardiograma', 'g/m2', null, '<95 (Mulher) e < 115 (Homem)', 7),
    ('Leucocitos', 'Leucograma', '/mm3', 'Leucócitos, ou glóbulos brancos, são células do sistema imunológico responsáveis pela defesa do organismo contra infecções e agentes patogênicos. Existem diferentes tipos de leucócitos, incluindo neutrófilos, linfócitos, monócitos, eosinófilos e basófilos, cada um com funções específicas na resposta imunológica. Os neutrófilos são os mais abundantes e são a primeira linha de defesa contra infecções bacterianas. Linfócitos, que incluem células T e B, são cruciais para a imunidade adaptativa, reconhecendo e lembrando patógenos específicos. Monócitos se transformam em macrófagos e fagocitam partículas estranhas. Eosinófilos combatem parasitas e participam de reações alérgicas, enquanto basófilos liberam histamina em resposta a alérgenos. A contagem de leucócitos no sangue pode indicar condições como infecções, inflamações ou doenças hematológicas [❞] [❞].', 'Adultos: 4.000 a 11.000 leucócitos por microlitro de sangue (4-11 x 10^9/L).', 1),
    ('Leucócitos Esterases', 'Sumário de Urina-EQ', null, null, null, 10),
    ('Leucócitos urina', 'Sumário de Urina-M', 'por campo', null, '<10 por campo', 2),
    ('Linfócitos', 'Leucograma', '%', null, '20 a 50 %', 7),
    ('Linfócitos atípicos', 'Leucograma', '%', null, '0 /mm3', 8),
    ('Magnésio', 'Específicos', 'mg/dL', null, '1,60 a 2,40 mg/dL', 19),
    ('Massa do VE', 'Ecocardiograma', 'gramas', null, '<163g (Mulher) e <225g (Homem)', 8),
    ('MDRD-Adulto não negro', 'Função Renal', 'mL/min/1.73m2', 'Ritimo de Filtração Glomerular.', 'Adulto >18 anos: >60 mL/min/1.73m2', 4),
    ('MDRD-Adulto negro', 'Função Renal', 'mL/min/1.73m2', 'Ritimo de Filtração Glomerular.', 'Adulto >18 anos: >60 mL/min/1.73m2', 5),
    ('Metamielócitos', 'Leucograma', '%', 'O metamielócito é uma célula da linhagem granulocítica da medula óssea, a mais madura após o mielócito.', '0', 5),
    ('Mielócitos', 'Leucograma', '%', 'Os mielócitos são glóbulos brancos ainda em fase de maturação. Tratam-se de neutrófilos jovens, um tipo de célula de defesa que faz parte do sistema imunológico. Quando o número de mielócitos está alto, significa que a medula óssea está tendo que produzir mais neutrófilos que o normal', '0 %', 6),
    ('Monócitos', 'Leucograma', '%', 'Os monócitos são um grupo de células do sistema imunológico que tem a função de defender o organismo de corpos estranhos, como vírus e bactérias. Quando os valores de monócitos ficam altos, condição também chamada de monocitose, pode significar a presença de infecções crônicas como tuberculose e colite ulcerativa, e problemas no sangue como leucemia monocítica aguda. Quando os valores de monócitos estão baixos, condição chamada de monocitopenia, normalmente significa que o sistema imunológico está enfraquecido, como acontece em casos de infecções no sangue, tratamentos de quimioterapia e problemas na medula óssea, como anemia aplástica e leucemia.', '2 a 10%', 9),
    ('MPV', 'Plaquetograma', 'fL', null, '6,8 a 11 fL', 2),
    ('Neutrófilos', 'Leucograma', '%', 'Os neutrófilos são um tipo de células do sangue que participam no combate às infecções. A sua quantidade pode aumentar nos casos de infecções (principalmente quando há presença de febre e pus em algum local), inflamações, tumores, sangramentos, uso de certas medicações, entre outras causas.', '30 a 60 %', 2),
    ('Nitrito', 'Sumário de Urina-EQ', '0=Negativo e 1 Positivo', null, null, 9),
    ('NT-proBNP', 'Específicos', 'pg/mL', null, '<75 anos: 125 pg/mL e >75 anos:450 pg/mL', 28),
    ('Paciente/Plasma Normal', 'Coagulograma', 's', null, null, 3),
    ('Paratormonio PTH', 'Específicos', 'PG/mL', null, '>  60 anos: 22 a 84 pg/mL', 32),
    ('Parede Posterior', 'Ecocardiograma', 'mm', null, '<11mm', 9),
    ('PCR', 'Marcadores Inflamatórios', 'mg/dL', 'Tipo especial de proteína produzida pelo fígado, que só aparece quando há infecções.', '<0,5 mg/dL', 1),
    ('Peso', 'Antropometria', 'Kg', null, null, 2),
    ('Peso Prostático', 'Próstata', 'gramas', null, null, 4),
    ('pH', 'Sumário de Urina-EQ', null, null, 'Até 7,5', 2),
    ('Plaquetas', 'Plaquetograma', '/mm3', null, '140.000 a 400.000', 1),
    ('Plaquetócrito', 'Plaquetograma', 'v/v', null, '0,12, a 0,36 v/v', 3),
    ('Plasma Controle do Dia', 'Coagulograma', null, null, null, 4),
    ('Plasma de Referência', 'Coagulograma', 's', null, null, 5),
    ('Potássio', 'Básicos', 'mmol/L', null, '3,5 a 5,1 mmol/L', 4),
    ('Pressão arterial diastólica', 'Sinais Vitais', 'mmHg', 'normalmente este valor é conhecido como a pressão arterial mínima, correspondente ao momento em que o ventrículo esquerdo volta a encher-se para retomar todo o processo da circulação. Este valor geralmente está dentro da média dos 80 mmHg.', null, 2),
    ('Pressão arterial sistólica', 'Sinais Vitais', 'mmHg', 'geralmente este valor é denominado de pressão arterial máxima, e é correspondente ao valor medido no momento em que o ventrículo esquerdo bombeia uma quantidade de sangue para a aorta. Normalmente este valor pode variar entre os 120 a 140 mmHg, sendo estes os valores mais comuns para que tenha a sua pressão dentro dos valores normais.', null, 1),
    ('Procalcitonina', 'Marcadores Inflamatórios', 'ng/mL', 'PCT representa risco de progressão para septicemia', 'Risco Baixo:< 0,5 ng/mL Risco Moderado:  0,5 e 2 ng/mL : Risco Alto :2 ngmL', 4),
    ('Prolactina', 'Marcadores Tumorais', 'ng/mL', 'A prolactina é um hormônio produzido pela hipófise, uma glândula localizada no cérebro. Seu papel principal é estimular a produção de leite nas mulheres após o parto, mas também tem funções importantes em homens e mulheres não gestantes, como ajudar na regulação do sistema imunológico, no metabolismo e até no comportamento reprodutivo.

Os níveis de prolactina podem ser medidos por um exame de sangue, e alterações nos seus níveis podem indicar diversas condições, como:

Hiperprolactinemia: níveis elevados de prolactina, que podem ser causados por gravidez, estresse, medicamentos, ou problemas na hipófise (como tumores chamados prolactinomas).

Hipoprolactinemia: níveis baixos de prolactina, que podem ocorrer em alguns transtornos hipofisários.


Os sintomas de níveis alterados de prolactina variam, podendo incluir distúrbios menstruais, produção de leite fora do período pós-parto, diminuição da libido e, em alguns casos, infertilidade.

Caso tenha interesse em mais detalhes sobre exames, causas ou sintomas específicos relacionados à prolactina, posso aprofundar essas informações.', 'Homem 2,7 a 17,7 ng/mL', 8),
    ('Promielocites', 'Leucograma', '%', null, null, 12),
    ('Proteínas', 'Sumário de Urina-EQ', 'mg/dL', null, '< 10mg/dL', 3),
    ('Proteinúria', 'Função Renal', 'mg/dia', 'A proteinúria pode ser um sinal de lesão renal com  perda excessiva de proteínas através da urina', 'Até 140 mg/dia', 3),
    ('Protrombina', 'Específicos', 's', null, null, 20),
    ('PSA', 'Próstata', '%', null, 'acima de 25%', 3),
    ('PSA livre', 'Próstata', 'ng/mL', null, null, 2),
    ('PSA Total', 'Próstata', 'ng/mL', null, null, 1),
    ('PWD', 'Plaquetograma', '%', null, '25 a 65 %', 4),
    ('Quadril', 'Antropometria', 'cm', null, null, 4),
    ('RDW', 'Eritrograma', '%', 'RDW (Red Cell Distribution Width) é um índice laboratorial que mede a variação no tamanho dos glóbulos vermelhos (hemácias) no sangue. Valores elevados de RDW indicam uma maior variabilidade no tamanho das hemácias, podendo sugerir condições como anemia, deficiências nutricionais (ferro, vitamina B12 ou folato) e doenças crônicas. Valores normais variam entre 11.5% e 14.5%. O RDW é usado em conjunto com outros índices hematológicos para ajudar no diagnóstico de diversas condições hematológicas.', '12.1 a 16.3 %', 7),
    ('Relação TTPA/PR', 'Ecocardiograma', null, null, 'Até 1,25', 10),
    ('RNI', 'Coagulograma', null, 'Relação Normatizada Internacional', null, 6),
    ('Sangue oculto Fezes', 'Específicos', null, 'O exame de sangue oculto avalia a presença de pequenas quantidades de sangue nas fezes, que podem não ser visíveis a olho nu. Ajuda a detectar a presença de sangramentos no intestino grosso, que podem ser sinais de úlceras, colite ou até câncer.', 'Positivo ou negativo', 40),
    ('Segmentados', 'Leucograma', '%', null, '30 a 60 %', 3),
    ('Septo Intraventricular', 'Ecocardiograma', 'mm', null, '<11mm', 11),
    ('SHBG', 'Específicos', 'nmol/L', null, 'Homem de 50 a 89 - 21,6 a 113,1 nmol/L', 50),
    ('Sódio', 'Básicos', 'mmol/L', null, '136 a 145 mmol/L', 5),
    ('SpO2', 'Sinais Vitais', '%', 'Saturação de pressão de Oxigêncio', null, 3),
    ('T4', 'Específicos', 'pmol/L', 'Quando os níveis de T3 e T4 estão muito reduzidos na circulação sanguínea, a hipófise secreta TSH. Este “avisa” à tireoide para começar a produzir mais hormônios tireoidianos. Leia mais http://www.mundoboaforma.com.br/tiroxina-t4-livre-o-que-e-funcao-e-exame/#5sYeWf5f16MTqPR3.99', '12 a 22 pmol/L', 21),
    ('Temperatura', 'Sinais Vitais', 'ºC', null, null, 5),
    ('Tempo de coagulação', 'Coagulograma', 'min', null, null, 10),
    ('Tempo de sangramento', 'Coagulograma', 'min', 'Tempo de sangramento', null, 9),
    ('Testosterona', 'Específicos', 'ng/dL', null, '165 a 753 ng/dL', 36),
    ('Testosterona Livre Calculada', 'Específicos', 'ng/dL', null, 'Homem: (21 a 49) 3,03 a 14,80, (50 a 89) 1,81 a 10,20', 37),
    ('Tiroxina Livre', 'Específicos', 'pmol/L', null, '9,69 a 23,16 pmol/L', 22),
    ('TP', 'Coagulograma', 's', null, null, 7),
    ('Triglicerídeos', 'Lipidograma', 'mg/dL', null, 'Com jejum: < 150 mg/dL e Sem jejum: < 175 mg/dL', 6),
    ('Tromboplatina P. Ativado', 'Específicos', 's', null, null, 23),
    ('Troponina I Ultra-Sensível', 'Específicos', 'ng/mL', null, '< 0,06 ng/mL', 24),
    ('Troponina T de Alta Sensibilidade', 'Específicos', 'ng/mL', null, '< 0,025 ng/mL', 30),
    ('TSH', 'Específicos', 'uUI/mL', null, '0,27 a 4,29 uUI/mL', 25),
    ('TSH Utra-Sensível', 'Específicos', 'mUI/mL', null, null, 26),
    ('TTPA', 'Coagulograma', 's', null, null, 8),
    ('Uréia', 'Função Renal', 'mg/dL', 'O exame de ureia é usado principalmente para avaliar a função dos rins. Atualmente, tem sua maior utilidade em clientes renais crônicos, uma vez que o exame de creatinina é mais utilizado para diagnóstico de problemas renais ou mesmo acompanhamento da função renal. Dessa forma, a dosagem sanguínea de ureia é um complemento da dosagem de creatinina. 

www.tuasaude.com/alimentacao-na-insuficiencia-renal/amp/

http://diariodefarmacia2010.blogspot.com/2012/05/avaliacao-da-funcao-renal.html?m=1', 'Crianças e Adolecentes: 5 a 35 mg/dL e Adultos: 15 a  45 mg/dL', 2),
    ('Urobilinogênio', 'Sumário de Urina-EQ', 'mg/dL', null, '< 2mg/dL', 7),
    ('Valor Globular', 'Eritrograma', null, 'O valor globular, cuja abreviatura é VG, consiste num coeficiente quantitativo do pigmento vermelho do sangue (hemoglobina) contido nos glóbulos vermelhos (eritrócitos). ... O valor globular é calculado dividindo a percentagem de hemoglobina pelo dobro dos dois primeiros algarismos do número de eritrócitos.', '0,8 a 1,10', 8),
    ('VCM', 'Eritrograma', 'fL', null, '80.0 a 100.0 fl', 4),
    ('Ventrículo direito (Apical)', 'Ecocardiograma', 'mm', null, '<41 mm', 15),
    ('VHS', 'Marcadores Inflamatórios', 'mm/h', 'significa a velocidade com que os glóbulos vermelhos se separam do “soro” e se depositam no fundo, se um tubo de sangue (com anti-coagulante) é deixado parado. O exame VHS serve para identificar a presença de processos inflamatórios ou infecciosos no organismo, como artrites, infecções bacterianas, entre outras doenças. Quando o resultado do exame VHS está muito alto (acima de 100 mm/h), pode ser sinal de infecção, inflamação no tecido conjuntivo ou ainda câncer.', '< 20 mm/h ou 3 a 9 mm', 2),
    ('Vitamina B12', 'Específicos', 'pg/mL', null, '197 a 771 pg/mL', 27),
    ('Volume Corpuscular Médio', 'Específicos', 'fL', null, '81,7 a 95,3', 31),
    ('Volume Diastólico F. do VE', 'Ecocardiograma', 'mL', null, null, 12),
    ('Volume Indexado do Átrio Esquerdo', 'Ecocardiograma', 'ml/mm2', null, '<34', 14),
    ('Volume Plaquetário Médio', 'Plaquetograma', 'fL', null, '9,2 a 12,6', 4),
    ('Volume Sistólico F. do VE', 'Ecocardiograma', 'mL', null, null, 13),
    ('Volume x', 'Próstata', 'cm', null, null, 5),
    ('Volume y', 'Próstata', 'cm', null, null, 6),
    ('Volume z', 'Próstata', 'cm', null, null, 7),
    ('H.C.G. BETA TOTAL (Qualitativo)', 'Específicos', 'mUI/ml', 'O **β-hCG total** é um hormônio glicoproteico produzido principalmente pelo tecido trofoblástico da placenta. Ele é composto por uma subunidade alfa comum a outros hormônios e uma subunidade beta específica, responsável pela sua identificação laboratorial. Sua principal função é manter o corpo lúteo no início da gestação, garantindo a produção de progesterona. O exame de β-hCG total é utilizado para diagnóstico e acompanhamento da gravidez. Em homens e mulheres não grávidas, níveis elevados podem indicar condições patológicas, como tumores produtores de hCG.', 'normal quando <5 mUI/mL em homens e mulheres não grávidas', 42),
    ('Globolina ligadora de hormônios sexuais', 'Específicos', 'nmol/L', null, 'Homem de 50 a 89 anos 21.2 a 159.1 nmol/L', 60)
)
insert into exam_catalog (name, group_id, unit, description, reference_range, source_position)
select
  exam_seed.name,
  exam_groups.id,
  exam_seed.unit,
  exam_seed.description,
  exam_seed.reference_range,
  exam_seed.source_position
from exam_seed
left join exam_groups on exam_groups.name = exam_seed.group_name
on conflict (name, group_id) do update set
  unit = excluded.unit,
  description = excluded.description,
  reference_range = excluded.reference_range,
  source_position = excluded.source_position;
